webtalk_init -webtalk_dir E:/fpga_projects/MicroStevie/MicroStevie.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 27 22:42:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3702c990-bd62-4e1b-a72b-49426ada6b5a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "974465e175f54c8e8f5a780ad76ef3b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "206" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3193 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "88523130 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "15.75_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14596_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1536219946 -regid "" -xml E:/fpga_projects/MicroStevie/MicroStevie.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/fpga_projects/MicroStevie/MicroStevie.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/fpga_projects/MicroStevie/MicroStevie.sim/sim_1/behav/xsim/xsim.dir/top_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
